version: 1
disable_existing_loggers: False
formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    use_colors: true
  access:
    "()": uvicorn.logging.AccessFormatter
    format: "[%(asctime)s %(process)d:%(threadName)s] %(name)s - %(levelname)s - %(message)s | %(filename)s:%(lineno)d"
    use_colors: true
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr

  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
    
  file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: access
    filename: info.log
    encoding: utf8
    mode: a

loggers:
  uvicorn.error:
    level: INFO
    handlers: [default]
    propagate: no

  uvicorn.access:
    level: INFO
    handlers: [access]
    propagate: no
